version: "3.8"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Laposta123456!
      MYSQL_DATABASE: db_sistema_ventas
      MYSQL_USER: fernandino
      MYSQL_PASSWORD: Laposta123456!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mi_red

  backend:
    build: ./
    container_name: sistema_backend
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/db_sistema_ventas?useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: fernandino
      SPRING_DATASOURCE_PASSWORD: Laposta123456!
    ports:
      - "8080:8080"
    networks:
      - mi_red

volumes:
  mysql_data:

networks:
  mi_red: